apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: seangammage/todo-api:latest  # <-- Update this to match your Docker Hub image
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql+asyncpg://user:password@postgres-service:5432/todo_db
